config/routes.rb
CourseProject::Application.routes.draw do
  
	ActiveAdmin.routes(self)

	devise_for :admin_users, ActiveAdmin::Devise.config

	devise_for :users, :path => 'accounts', controllers: { confirmations: 'confirmations' }

   	devise_scope :user do
  		get '/confirmation-getting-started' => 'userdetails#new', as: 'confirmation_getting_started'
	end
  
	root to: "main#index"
	resources :userdetails, only: [:create, :new, :show, :edit, :update]
	resources :clubs, only: [:create, :new, :show, :edit, :update]
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/club.rb
class Club < ActiveRecord::Base

	attr_accessible :name, :image, :location, :timing, :capacity, :phone, :email, :url, :manager, :about

	mount_uploader :image, ClubimageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_one :userdetail
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/userdetail.rb
class Userdetail < ActiveRecord::Base

	belongs_to :user
	attr_accessible :firstname, :lastname, :gender, :image, :birthyear, :city, :country, :zipcode

	mount_uploader :image, UserimageUploader
	validates :firstname, :lastname, :gender, :image, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	def after_sign_in_path_for(resource_or_scope)
		if resource_or_scope.is_a?(User) && current_user.last_sign_in_at.nil?
			redirect_to :controller => :userdetails, :action => :new
		else
			super
		end
	end


end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

	def new
		
	end

	def create
		
	end

	def edit
		
	end

	def update
		
	end

	def show
		@club = Club.find(params[:id])
	end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  def new
    super
  end

  def create
    super
  end

  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])

    if resource.errors.empty?
      set_flash_message(:notice, :confirmed) if is_navigational_format?
      sign_in(resource_name, resource)
      respond_with_navigational(resource) { redirect_to new_user_confirmation_path }
    else
      respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render_with_scope :new }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
  	if user_signed_in?
		if current_user.userdetail.nil? 
		   @userdetail = Userdetail.new
           redirect_to new_userdetail_path
        else
        	@clubs = Club.order('created_at DESC').all
		end
	else
		@clubs = Club.order('created_at DESC').all
	end	
  end
end

app/controllers/userdetails_controller.rb
class UserdetailsController < ApplicationController

	def new
		@userdetail = Userdetail.new
	end

	def create
		@userdetail = Userdetail.new(params[:userdetail])
		@userdetail.user = current_user
		if @userdetail.save
			redirect_to root_path, :notice => "Updated successfully"
		else
			render "new"
		end		
	end

	def edit
		@user = current_user
		@userdetail = @user.userdetail
	end

	def update
		@user = current_user
		@userdetail = @user.userdetail
		if @userdetail.update_attributes(params[:userdetail])
			redirect_to root_path, notice: "Updated successfully"
		else
			render "edit", error: "There might be some problem updating it now"
		end		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active(page)
		return 'class="active"'.html_safe if current_page?(page)
	end
	
end

app/helpers/clubs_helper.rb
module ClubsHelper

	def url_helper(url_data)
		if url_data.url.starts_with?("http://")
			link_to url_data.url, url_data.url
		elsif url_data.url.to_s ==''
			"Url not updated".html_safe
		else
			link_to url_data.url, "http://" + url_data.url
		end	
	end

end	

app/views/clubs/show.html.erb
<%= @club.name %><br/>
<%= url_helper(@club)  %><br/>
<%= @club.capacity %><br/>
<%= @club.location %><br/>
<%= @club.timing %><br/>
<%= @club.phone %><br/>
<%= @club.email %><br/>
<%= @club.about.html_safe %>
<%= "-----" %> <br/>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
 
<!-- Be sure to leave the brand out there if you want it shown -->
<div class="brand"> <%= link_to "After-hours-cliq", root_path %></div>
 
<!-- Everything you want hidden at 940px or less, place within here -->
<div class="nav-collapse collapse">
<!-- .nav, .navbar-search, .navbar-form, etc -->
    <ul class="nav">
        <li <%= active(root_path) %> ><%= link_to "Home", root_path %></li>
        <% if current_user %>
            <li><%= link_to("Sign out", destroy_user_session_path, :method=>'delete') %></li>
            <% if current_user.userdetail.nil? %>
                <li <%= active(new_userdetail_path) %> ><%= link_to('Profile', new_userdetail_path) %></li>
            <% else %>
                <li <%= active(edit_userdetail_path(current_user)) %> ><%= link_to('Profile', edit_userdetail_path(current_user)) %> </li>
            <% end %>

        <% else %>    
            <li <%= active(new_user_session_path) %> ><%= link_to "Sign in", new_user_session_path %></li>
            <li <%= active(new_user_registration_path) %> ><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>    
        
     </ul>   
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Afterhourscliq" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <br/>
            &copy; <a href='http://afterhourscliq.com'>Afterhourscliq</a> <%= Time.now.year %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/main/index.html.erb
<ul class="thumbnails row-fluid">
	<% @clubs.each do |club| %>
		<li class="span2">
			<div class="thumbnail">
				<%= image_tag(club.image, :class => "image-polaroid") %>
				<h3 class="text-center"><%= club.name[0,10] %></h3>
				<% if false %>
					<span class="label label-info">URL:</span> <%= url_helper(club) %><br/>
					<span class="label label-info">Capacity:</span> <%= club.capacity %><br/>
					<span class="label label-info">Location:</span> <%= club.location %><br/>
					<span class="label label-info">Timing:</span> <%= club.timing %><br/>
					<span class="label label-info">Phone:</span> <%= club.phone %><br/>
					<span class="label label-info">Email:</span> <%= club.email %><br/>
				
					<p><%= truncate(club.about.html_safe, :length => 1000) %></p>
				<% end %>	
				<p><%= truncate_html(club.about, length: 50, omission: '...') %></p>
				<div class="text-right"><%= link_to "more...", club_path(club)%></div>
				
				<% if current_user %>
					<div class="text-center">Are you coming today? </div>
					<button class="text-center btn btn-block btn-success" type="button">Will be there tonight</button>

				<% else %>
					<%= link_to "Log in", new_user_session_path %>  to connect to others coming today...
				<% end %>	
				
			</div>

		</li>
	<% end %>
	
</ul>

app/views/userdetails/edit.html.erb
<h4>UPDATE YOUR PROFILE:</h4><br/>

welcome... <%= current_user.email %><br/><br/>

 <%= form_for @userdetail, :html => {:multipart => true}, method: "put" do |f| %>
	<% if @userdetail.errors.any? %>
		<div class="alert alert-error">
			<%= @userdetail.errors.full_messages.join("<br/>").html_safe %>
		</div>
	<% end %>

	<div class="row-fluid">	
		
		<%= f.label :firstname, "FIRST NAME:" %>
		<%= f.text_field :firstname, class: "span3", placeholder: "First Name" %><br/>
		
		<%= f.label :lastname, "LAST NAME:" %>
		<%= f.text_field :lastname, class: "span3", placeholder: "Last Name" %><br/>
		
		<%= f.label :gender, "GENDER:" %>
		<%= select(:userdetail, :gender, %w[Male Female], {:prompt => "Select gender"}, :class => "span3") %>
		
		<%= f.label :image, "PROFILE IMAGE:" %>
		<%= f.file_field :image %><br/>

		
		<%= f.label :city, "CITY:" %>
		<%= f.text_field :city, class: "span3", placeholder: "Current Location / City" %><br/>
		
		<%= f.label :country, "COUNTRY:" %>
		<%= country_select(:userdetail, :country, "select country") %><br/>

		<%= f.label :zipcode, "ZIP CODE:" %>
		<%= f.text_field :zipcode, class: "span3", placeholder: "zip_code" %><br/>
		
		<%= f.label :birthyear, "YEAR OF BIRTH (e.g. 1980):" %>
		<%= f.text_field :birthyear, class: "span3", placeholder: "e.g. 1980" %><br/>
	
		<%= f.submit "Update your profile!", class: "btn btn-large btn-primary" %>
	</div>	
<% end %>


  		

app/views/userdetails/new.html.erb
welcome... <%= current_user.email %><br/><br/>

<div class="alert alert-info">	
	Update your information to explore further...Don't worry it's safe with us.
</div>	

 <%= form_for @userdetail, :html => {:multipart => true} do |f| %>
	<% if @userdetail.errors.any? %>
		<div class="alert alert-error">
			<%= @userdetail.errors.full_messages.join("<br/>").html_safe %>
		</div>
	<% end %>

	<div class="row-fluid">	
		
		<%= f.label :firstname, "FIRST NAME:" %>
		<%= f.text_field :firstname, class: "span3", placeholder: "First Name" %><br/>
		
		<%= f.label :lastname, "LAST NAME:" %>
		<%= f.text_field :lastname, class: "span3", placeholder: "Last Name" %><br/>
		
		<%= f.label :gender, "GENDER:" %>
		<%= select(:userdetail, :gender, %w[Male Female], {:prompt => "Select gender"}, :class => "span3") %>
		
		<%= f.label :image, "PROFILE IMAGE:" %>
		<%= f.file_field :image %><br/>

		
		<br/><div class="muted">OPTIONAL FILEDS:</div>

		<%= f.label :city, "CITY:" %>
		<%= f.text_field :city, class: "span3", placeholder: "Current Location / City" %><br/>
		
		<%= f.label :country, "COUNTRY:" %>
		<%= country_select(:userdetail, :country, "select country") %><br/>

		<%= f.label :zipcode, "ZIP CODE:" %>
		<%= f.text_field :zipcode, class: "span3", placeholder: "zip_code" %><br/>
		
		<%= f.label :birthyear, "YEAR OF BIRTH (e.g. 1980):" %>
		<%= f.text_field :birthyear, class: "span3", placeholder: "e.g. 1980" %><br/>
	
		<%= f.submit "Create your profile!", class: "btn btn-large btn-primary" %>
	</div>	
<% end %>


  		

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>